### ISSUE TITLE
What about 2+4?

### ISSUE THREAD

**Issue by starryknight64** [viperior/two-sum-problem#1]
Was curious in your example why wouldn't [1,3] (2+4=6) be a possible output? Does the algorithm just pick the two smallest numbers in the given set?

**Comment by dagpunk** [comment]
Thank you for your question. Your observation of the second solution is valid. I plan to change the example input to better align with the stated assumptions. Perhaps I can give another example of input with multiple solutions in a separate section.

In those cases where there are multiple solutions, my solution doesn't try to find them all. It will identify the first valid pair of input elements matching the target sum and return them immediately.

It would be interesting to write a solution that finds all the possible solutions, but that adds additional optimization challenges.

At any rate, stay tuned for a new version that will correct that example.

**Comment by dagpunk** [comment]
I resolved this is [v1.1.0](https://github.com/viperior/two-sum-problem/releases/tag/v1.1.0) by replacing the original example with this:

## Example Test Case
### Inputs
* List of integers = [3, 2, 95, 4, -3]
* Target sum = 92

### Output
[2, 4], because 95 + -3 = 92

Now a reader won't be distracted by the multiple-solution aspect, and this example also shows how negative numbers are handled.
